#!/usr/bin/env python3
"""Generate docs/DASHBOARD.md from daily nightly report JSON files.

Reads all ~/.hindsight/logs/YYYY-MM-DD.json files and produces a
markdown dashboard with daily metrics tables and trend indicators.

Called by the nightly pipeline after the daily report is written.
Can also be run standalone: python3 generate-dashboard.py
"""

import json
import os
from datetime import date, datetime
from glob import glob
from pathlib import Path

LOG_DIR = Path(os.path.expanduser("~/.hindsight/logs"))
DASHBOARD_PATH = Path(__file__).resolve().parent / "docs" / "DASHBOARD.md"
EPOCH_START_DATE = "2026-06-26"


def load_reports() -> list[dict]:
    files = sorted(glob(str(LOG_DIR / "2???-??-??.json")))
    reports = []
    for f in files:
        with open(f) as fh:
            d = json.load(fh)
        d.setdefault("date", Path(f).stem)
        reports.append(d)
    return reports


def fmt(val, fmt_str=".2f", fallback="—"):
    if val is None:
        return fallback
    return f"{val:{fmt_str}}"


def pct(val, fallback="—"):
    if val is None:
        return fallback
    return f"{val:.1f}%"


def trend(current, previous):
    if current is None or previous is None:
        return ""
    diff = current - previous
    if abs(diff) < 0.01:
        return " ="
    return " ↑" if diff > 0 else " ↓"


def generate_dashboard(reports: list[dict]) -> str:
    lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    epoch = date.fromisoformat(EPOCH_START_DATE)
    days_since_epoch = (date.today() - epoch).days

    lines.append("# Engram Effectiveness Dashboard")
    lines.append("")
    lines.append(f"> Auto-generated by `generate-dashboard.py` — last updated **{now}**")
    lines.append(">")
    lines.append(f"> Epoch: **{EPOCH_START_DATE}** ({days_since_epoch} days ago)")
    if days_since_epoch < 7:
        lines.append(f"> Stabilization window: **{7 - days_since_epoch} days remaining**")
    else:
        lines.append("> Stabilization window: **complete**")
    lines.append(">")
    lines.append("> See [Metrics and Monitoring](METRICS.md) for metric definitions.")
    lines.append("")

    # --- Latest snapshot ---
    latest = reports[-1]
    prev = reports[-2] if len(reports) > 1 else {}
    eff = latest.get("effectiveness", {})
    e = eff.get("effectiveness", {})
    pr = eff.get("proactive_recall", {})
    bs = latest.get("bank_stats", {})
    tri = latest.get("triage", {})
    rs = eff.get("recall_session_stats", {})

    prev_eff = prev.get("effectiveness", {})
    prev_e = prev_eff.get("effectiveness", {})
    prev_rs = prev_eff.get("recall_session_stats", {})

    lines.append(f"## Latest ({latest.get('date', '?')})")
    lines.append("")
    lines.append("| Metric | Value | Prev |")
    lines.append("|--------|------:|-----:|")

    cw = e.get("corrections_per_session_with_recall")
    pcw = prev_e.get("corrections_per_session_with_recall")
    lines.append(f"| Corrections/session (recall) | {fmt(cw)}{trend(cw, pcw)} | {fmt(pcw)} |")

    rw_pct = rs.get("avg_rework_pct")
    prw_pct = prev_rs.get("avg_rework_pct")
    lines.append(f"| Rework % | {pct(rw_pct)}{trend(rw_pct, prw_pct)} | {pct(prw_pct)} |")

    pd = rs.get("avg_productivity_density")
    ppd = prev_rs.get("avg_productivity_density")
    lines.append(f"| Productivity density | {fmt(pd, '.4f')}{trend(pd, ppd)} | {fmt(ppd, '.4f')} |")

    fpt = rs.get("avg_first_productive_turn")
    pfpt = prev_rs.get("avg_first_productive_turn")
    lines.append(f"| First productive turn | {fmt(fpt, '.1f')}{trend(fpt, pfpt)} | {fmt(pfpt, '.1f')} |")

    ra = pr.get("recall_adoption_pct")
    pra = prev.get("effectiveness", {}).get("proactive_recall", {}).get("recall_adoption_pct")
    lines.append(f"| Recall adoption | {pct(ra)}{trend(ra, pra)} | {pct(pra)} |")

    pp = pr.get("proactive_pct")
    ppp = prev.get("effectiveness", {}).get("proactive_recall", {}).get("proactive_pct")
    lines.append(f"| Proactive recall | {pct(pp)}{trend(pp, ppp)} | {pct(ppp)} |")

    lines.append("")

    # --- Session Distribution ---
    dist = eff.get("session_distribution", {})
    if dist:
        lines.append("## Session Distribution")
        lines.append("")
        lines.append("| Bucket | With Recall | Without Recall | Total |")
        lines.append("|--------|----------:|---------------:|------:|")
        bucket_labels = {
            "trivial": "Trivial (<5K)",
            "small": "Small (5-15K)",
            "medium": "Medium (15-100K)",
            "large": "Large (>100K)",
        }
        for bucket in ("trivial", "small", "medium", "large"):
            if bucket in dist:
                wr = dist[bucket].get("with_recall", 0)
                wor = dist[bucket].get("without_recall", 0)
                lines.append(f"| {bucket_labels[bucket]} | {wr} | {wor} | {wr + wor} |")
        lines.append("")

    # --- Weekly Trend ---
    weekly = eff.get("weekly_trend", [])
    if weekly:
        lines.append("## Weekly Trend (recall sessions, from epoch)")
        lines.append("")
        lines.append("| Week | Sessions | Corr/Sess | Rework % | Prod Density | 1st Prod Turn |")
        lines.append("|------|--------:|----------:|---------:|-------------:|--------------:|")
        for wk in weekly:
            lines.append(
                f"| {wk['week']}"
                f" | {wk['sessions']}"
                f" | {wk['corrections_per_session']:.2f}"
                f" | {wk['rework_pct']:.1f}%"
                f" | {wk['productivity_density']:.4f}"
                f" | {wk['first_productive_turn']:.1f} |"
            )
        lines.append("")

    # --- Memory banks ---
    lines.append("## Memory Banks")
    lines.append("")
    lines.append("| Bank | Nodes | Documents | Pending |")
    lines.append("|------|------:|----------:|--------:|")
    for bank_key, label in [
        ("cursor-memory", "cursor-memory"),
        ("kubernaut-docs", "kubernaut-docs"),
        ("kubernaut-issues", "kubernaut-issues"),
    ]:
        b = bs.get(bank_key, {})
        nodes = b.get("total_nodes")
        docs = b.get("total_documents")
        pending = b.get("pending_consolidation")
        lines.append(
            f"| {label} | {fmt(nodes, ',d') if nodes else '—'}"
            f" | {fmt(docs, ',d') if docs else '—'}"
            f" | {fmt(pending, ',d') if pending else '—'} |"
        )
    lines.append("")

    # --- Triage ---
    if tri:
        lines.append("## Triage (latest)")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|------:|")
        lines.append(f"| Memories scanned | {tri.get('total_memories', '—')} |")
        lines.append(f"| Flagged | {tri.get('total_flagged', '—')} ({pct(tri.get('flagged_pct'))}) |")
        by_reason = tri.get("by_reason", {})
        for reason, count in sorted(by_reason.items(), key=lambda x: -x[1]):
            lines.append(f"| &nbsp;&nbsp;{reason} | {count} |")
        lines.append(f"| Docs rearranged | {tri.get('docs_rearranged', 0)} |")
        lines.append(f"| Docs deleted | {tri.get('docs_deleted', 0)} |")
        lines.append(f"| Memories removed | {tri.get('memories_removed', 0)} |")
        lines.append("")

    # --- Hit rates ---
    mcp = eff.get("mcp_usage", {})
    if mcp:
        lines.append("## MCP Hit Rates")
        lines.append("")
        lines.append("| Server | Calls | Hits | Hit Rate |")
        lines.append("|--------|------:|-----:|---------:|")
        for srv in sorted(mcp.keys()):
            s = mcp[srv]
            calls = s.get("calls", 0)
            hits = s.get("hits", 0)
            hr = s.get("hit_rate")
            lines.append(f"| {srv} | {calls} | {hits} | {pct(hr * 100 if hr is not None else None)} |")
        lines.append("")

    # --- Daily trend table (post-epoch only) ---
    post_epoch = [r for r in reports if r.get("date", "") >= EPOCH_START_DATE]
    if post_epoch:
        lines.append("## Daily Trend (post-epoch)")
        lines.append("")
        lines.append(
            "| Date | Sessions | Corrections | Corr/sess (w/) | Rework %"
            " | Prod Density | Adoption | Memories |"
        )
        lines.append("|------|--------:|-----------:|--------------:|---------:"
                     "|-------------:|---------:|---------:|")

        for r in post_epoch:
            d = r.get("date", "?")
            eff_r = r.get("effectiveness", {})
            e_r = eff_r.get("effectiveness", {})
            pr_r = eff_r.get("proactive_recall", {})
            rs_r = eff_r.get("recall_session_stats", {})
            bs_r = r.get("bank_stats", {}).get("cursor-memory", {})

            sw = e_r.get("sessions_with_recall", 0)
            swo = e_r.get("sessions_without_recall", 0)
            sessions = (sw or 0) + (swo or 0) if sw is not None or swo is not None else None

            lines.append(
                f"| {d}"
                f" | {fmt(sessions, 'd') if sessions else '—'}"
                f" | {r.get('corrections_detected', '—')}"
                f" | {fmt(e_r.get('corrections_per_session_with_recall'))}"
                f" | {pct(rs_r.get('avg_rework_pct'))}"
                f" | {fmt(rs_r.get('avg_productivity_density'), '.4f')}"
                f" | {pct(pr_r.get('recall_adoption_pct'))}"
                f" | {fmt(bs_r.get('total_nodes'), ',d') if bs_r.get('total_nodes') else '—'}"
                f" |"
            )

    lines.append("")

    # --- Notes ---
    lines.append("## Notes")
    lines.append("")
    lines.append("- **Epoch**: June 26, 2026 — rules consolidated, planning gate added, CocoIndex integrated")
    lines.append("- **Corrections/session**: lower is better (recall sessions with fewer corrections)")
    lines.append("- **Rework %**: lower is better (less time on correction loops)")
    lines.append("- **Productivity density**: higher is better (more productive actions per 1K tokens)")
    lines.append("- **First productive turn**: lower is better (agent starts real work sooner)")
    lines.append("- Pre-epoch data archived but not shown (collected under different rules, not comparable)")
    lines.append("")

    return "\n".join(lines)


def main():
    reports = load_reports()
    if not reports:
        print("No daily reports found in", LOG_DIR)
        return
    dashboard = generate_dashboard(reports)
    DASHBOARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    DASHBOARD_PATH.write_text(dashboard)
    print(f"Dashboard written to {DASHBOARD_PATH} ({len(reports)} days)")


if __name__ == "__main__":
    main()
