#!/usr/bin/env python3
"""Generate docs/DASHBOARD.md from daily nightly report JSON files.

Reads all ~/.hindsight/logs/YYYY-MM-DD.json files and produces a
markdown dashboard with daily metrics tables and trend indicators.

Called by the nightly pipeline after the daily report is written.
Can also be run standalone: python3 generate-dashboard.py
"""

import json
import os
from datetime import datetime
from glob import glob
from pathlib import Path

LOG_DIR = Path(os.path.expanduser("~/.hindsight/logs"))
DASHBOARD_PATH = Path(__file__).resolve().parent / "docs" / "DASHBOARD.md"


def load_reports() -> list[dict]:
    files = sorted(glob(str(LOG_DIR / "2???-??-??.json")))
    reports = []
    for f in files:
        with open(f) as fh:
            d = json.load(fh)
        d.setdefault("date", Path(f).stem)
        reports.append(d)
    return reports


def fmt(val, fmt_str=".2f", fallback="—"):
    if val is None:
        return fallback
    return f"{val:{fmt_str}}"


def pct(val, fallback="—"):
    if val is None:
        return fallback
    return f"{val:.1f}%"


def trend(current, previous):
    if current is None or previous is None:
        return ""
    diff = current - previous
    if abs(diff) < 0.01:
        return " ="
    return " ↑" if diff > 0 else " ↓"


def generate_dashboard(reports: list[dict]) -> str:
    lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines.append("# Engram Effectiveness Dashboard")
    lines.append("")
    lines.append(f"> Auto-generated by `generate-dashboard.py` — last updated **{now}**")
    lines.append(">")
    lines.append("> See [Metrics and Monitoring](METRICS.md) for metric definitions.")
    lines.append("")

    # --- Latest snapshot ---
    latest = reports[-1]
    prev = reports[-2] if len(reports) > 1 else {}
    eff = latest.get("effectiveness", {})
    k = eff.get("k_curve", {})
    nes = eff.get("net_efficiency_score", {})
    e = eff.get("effectiveness", {})
    pr = eff.get("proactive_recall", {})
    bs = latest.get("bank_stats", {})
    tri = latest.get("triage", {})

    prev_eff = prev.get("effectiveness", {})
    prev_k = prev_eff.get("k_curve", {})
    prev_nes = prev_eff.get("net_efficiency_score", {})
    prev_e = prev_eff.get("effectiveness", {})

    lines.append(f"## Latest ({latest.get('date', '?')})")
    lines.append("")
    lines.append("| Metric | Value | Prev |")
    lines.append("|--------|------:|-----:|")

    k_score = k.get("k_score")
    pk = prev_k.get("k_score")
    lines.append(f"| K-score | {fmt(k_score)}{trend(k_score, pk)} | {fmt(pk)} |")

    nes_w = nes.get("with_recall", {}).get("nes")
    pnes_w = prev_nes.get("with_recall", {}).get("nes")
    lines.append(f"| NES (with recall) | {fmt(nes_w)}{trend(nes_w, pnes_w)} | {fmt(pnes_w)} |")

    nes_r = nes.get("nes_ratio")
    pnes_r = prev_nes.get("nes_ratio")
    lines.append(f"| NES ratio | {fmt(nes_r)}{trend(nes_r, pnes_r)} | {fmt(pnes_r)} |")

    cw = e.get("corrections_per_session_with_recall")
    pcw = prev_e.get("corrections_per_session_with_recall")
    lines.append(f"| Corrections/session (recall) | {fmt(cw)}{trend(cw, pcw)} | {fmt(pcw)} |")

    cwo = e.get("corrections_per_session_without_recall")
    pcwo = prev_e.get("corrections_per_session_without_recall")
    lines.append(f"| Corrections/session (no recall) | {fmt(cwo)} | {fmt(pcwo)} |")

    ra = pr.get("recall_adoption_pct")
    pra = prev.get("effectiveness", {}).get("proactive_recall", {}).get("recall_adoption_pct")
    lines.append(f"| Recall adoption | {pct(ra)}{trend(ra, pra)} | {pct(pra)} |")

    pp = pr.get("proactive_pct")
    ppp = prev.get("effectiveness", {}).get("proactive_recall", {}).get("proactive_pct")
    lines.append(f"| Proactive recall | {pct(pp)}{trend(pp, ppp)} | {pct(ppp)} |")

    lines.append("")

    # --- Memory banks ---
    lines.append("## Memory Banks")
    lines.append("")
    lines.append("| Bank | Nodes | Documents | Pending |")
    lines.append("|------|------:|----------:|--------:|")
    for bank_key, label in [
        ("cursor-memory", "cursor-memory"),
        ("kubernaut-docs", "kubernaut-docs"),
        ("kubernaut-issues", "kubernaut-issues"),
    ]:
        b = bs.get(bank_key, {})
        nodes = b.get("total_nodes")
        docs = b.get("total_documents")
        pending = b.get("pending_consolidation")
        lines.append(
            f"| {label} | {fmt(nodes, ',d') if nodes else '—'}"
            f" | {fmt(docs, ',d') if docs else '—'}"
            f" | {fmt(pending, ',d') if pending else '—'} |"
        )
    lines.append("")

    # --- Triage ---
    if tri:
        lines.append("## Triage (latest)")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|------:|")
        lines.append(f"| Memories scanned | {tri.get('total_memories', '—')} |")
        lines.append(f"| Flagged | {tri.get('total_flagged', '—')} ({pct(tri.get('flagged_pct'))}) |")
        by_reason = tri.get("by_reason", {})
        for reason, count in sorted(by_reason.items(), key=lambda x: -x[1]):
            lines.append(f"| &nbsp;&nbsp;{reason} | {count} |")
        lines.append(f"| Docs rearranged | {tri.get('docs_rearranged', 0)} |")
        lines.append(f"| Docs deleted | {tri.get('docs_deleted', 0)} |")
        lines.append(f"| Memories removed | {tri.get('memories_removed', 0)} |")
        lines.append("")

    # --- Hit rates ---
    mcp = eff.get("mcp_usage", {})
    if mcp:
        lines.append("## MCP Hit Rates")
        lines.append("")
        lines.append("| Server | Calls | Hits | Hit Rate |")
        lines.append("|--------|------:|-----:|---------:|")
        for srv in sorted(mcp.keys()):
            s = mcp[srv]
            calls = s.get("calls", 0)
            hits = s.get("hits", 0)
            hr = s.get("hit_rate")
            lines.append(f"| {srv} | {calls} | {hits} | {pct(hr * 100 if hr is not None else None)} |")
        lines.append("")

    # --- Daily trend table ---
    lines.append("## Daily Trend")
    lines.append("")
    lines.append(
        "| Date | Sessions | Corrections | K-score | NES (w/) | NES ratio"
        " | Corr/sess (w/) | Adoption | Memories |"
    )
    lines.append("|------|--------:|-----------:|--------:|---------:|----------:"
                 "|--------------:|---------:|---------:|")

    for r in reports:
        d = r.get("date", "?")
        eff_r = r.get("effectiveness", {})
        k_r = eff_r.get("k_curve", {})
        nes_r = eff_r.get("net_efficiency_score", {})
        e_r = eff_r.get("effectiveness", {})
        pr_r = eff_r.get("proactive_recall", {})
        bs_r = r.get("bank_stats", {}).get("cursor-memory", {})

        sw = e_r.get("sessions_with_recall", 0)
        swo = e_r.get("sessions_without_recall", 0)
        sessions = (sw or 0) + (swo or 0) if sw is not None or swo is not None else None

        lines.append(
            f"| {d}"
            f" | {fmt(sessions, 'd') if sessions else '—'}"
            f" | {r.get('corrections_detected', '—')}"
            f" | {fmt(k_r.get('k_score'))}"
            f" | {fmt(nes_r.get('with_recall', {}).get('nes'))}"
            f" | {fmt(nes_r.get('nes_ratio'))}"
            f" | {fmt(e_r.get('corrections_per_session_with_recall'))}"
            f" | {pct(pr_r.get('recall_adoption_pct'))}"
            f" | {fmt(bs_r.get('total_nodes'), ',d') if bs_r.get('total_nodes') else '—'}"
            f" |"
        )

    lines.append("")

    # --- Notes ---
    lines.append("## Notes")
    lines.append("")
    lines.append("- **K-score > 1.0**: recall sessions are more token-efficient per productive action")
    lines.append("- **NES closer to 1.0**: less rework; NES ratio > 1.0 means recall reduces rework")
    lines.append("- **Corrections/session**: lower is better; compare with-recall vs without")
    lines.append("- **Jun 20 memory drop**: triage bug caused data loss; recovered via `recover-memories.py` (see [FINDINGS.md](FINDINGS.md))")
    lines.append("- **Jun 22 gap**: computer was shut down, no nightly run")
    lines.append("- **Jun 23+ bank growth**: CocoIndex real-time ingestion replaced batch scripts")
    lines.append("")

    return "\n".join(lines)


def main():
    reports = load_reports()
    if not reports:
        print("No daily reports found in", LOG_DIR)
        return
    dashboard = generate_dashboard(reports)
    DASHBOARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    DASHBOARD_PATH.write_text(dashboard)
    print(f"Dashboard written to {DASHBOARD_PATH} ({len(reports)} days)")


if __name__ == "__main__":
    main()
